package com.engine.nnue_trainer.v3;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.engine.nnue_trainer.board.Board;
import com.engine.nnue_trainer.board.Cell;
import com.engine.nnue_trainer.board.CellKind;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

/**
 * Cross-language parity: {@link NNUEv3Evaluator} must reproduce the Python fit on real corpus
 * boards. The fixture is generated by {@code python/v3/gen_v3_eval_fixture.py} with the fitter's
 * own arithmetic ({@code fit_capacity.design} @ the shipped weights).
 *
 * <p>This is the test that makes everything downstream meaningful: a disagreement here means the
 * index mapping or the perspective normalization is wrong, and the leaf is evaluating a different
 * model than the one whose R2 was measured. After a refit, regenerate the fixture — the expected
 * scores belong to a specific {@code nnue_v3_weights.json}.
 */
public class V3EvalParityTest {

  private static final Path FIXTURE =
      Path.of("src", "test", "resources", "v3", "eval_parity_fixture.json");

  // Sequential double adds here vs numpy's dot product there: same values, different summation
  // order. Scores run to ~3e4, so this is still ~1e-9 relative — tight enough that a single
  // misplaced feature (weights are O(100)) fails loudly.
  private static final double TOL = 1e-5;

  @Test
  public void testMatchesPythonFixture() throws Exception {
    JsonNode doc = new ObjectMapper().readTree(FIXTURE.toFile());
    NNUEv3Evaluator ev = NNUEv3Evaluator.load(NNUEv3Evaluator.DEFAULT_WEIGHTS);

    int checked = 0;
    for (JsonNode fx : doc.get("fixtures")) {
      String name = fx.get("name").asText();
      double actual = ev.evaluate(reconstruct(fx), fx.get("stm").asInt());
      assertEquals(fx.get("expected").asDouble(), actual, TOL, name);
      checked++;
    }
    assertTrue(checked >= 8, "fixture must cover several boards, got " + checked);
  }

  private static Board reconstruct(JsonNode fx) {
    Board b = new Board(NNUEv3Accumulator.BOARD, NNUEv3Accumulator.BOARD);
    for (JsonNode cell : fx.get("cells")) {
      b.setCell(
          cell.get("r").asInt(),
          cell.get("c").asInt(),
          new Cell(cell.get("owner").asInt(), CellKind.valueOf(cell.get("kind").asText())));
    }
    return b;
  }
}
