package com.engine.nnue_trainer.v3;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.engine.nnue_trainer.board.Board;
import com.engine.nnue_trainer.board.Cell;
import com.engine.nnue_trainer.board.CellKind;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

/**
 * Cross-language parity for {@link NNUEv3NetEvaluator}: Java must reproduce the Python forward pass
 * on real corpus boards. The fixture is generated by {@code scripts/gen_v3_net_fixture.py} from the
 * same boards the linear evaluator's fixture uses, scored with numpy ({@code w2 @ relu(b1 + w1[:,
 * active].sum(1)) + b2}).
 *
 * <p>This is the load-bearing test: if Java and Python disagree here, the index mapping or the
 * ReLU/accumulator arithmetic is wrong, and every downstream number (R², gauntlet, NPS) is
 * measuring a different model than the one that was fitted. After a retrain, regenerate the fixture
 * — the expected scores belong to the specific weights file named in {@code meta.weights}.
 */
public class V3NetParityTest {

  private static final Path FIXTURE =
      Path.of("src", "test", "resources", "v3", "net_parity_fixture.json");

  // 144 sequential double adds per hidden unit here vs a numpy column sum there: same values,
  // different summation order. Scores run to ~1e4, so ~1e-9 relative — tight enough that a single
  // misplaced feature fails loudly.
  private static final double TOL = 1e-6;

  @Test
  public void testMatchesPythonFixture() throws Exception {
    JsonNode doc = new ObjectMapper().readTree(FIXTURE.toFile());
    Path weights = Path.of(doc.get("meta").get("weights").asText());
    assertTrue(
        Files.exists(weights),
        "fixture names weights "
            + weights
            + " which does not exist; regenerate with scripts/gen_v3_net_fixture.py");
    NNUEv3NetEvaluator ev = NNUEv3NetEvaluator.load(weights);
    assertEquals(doc.get("meta").get("hidden").asInt(), ev.hidden(), "hidden size");

    int checked = 0;
    for (JsonNode fx : doc.get("fixtures")) {
      double expected = fx.get("expected").asDouble();
      double actual = ev.evaluate(reconstruct(fx), fx.get("stm").asInt());
      assertEquals(
          expected, actual, Math.max(TOL, Math.abs(expected) * 1e-9), fx.get("name").asText());
      checked++;
    }
    assertTrue(checked >= 8, "fixture must cover several boards, got " + checked);
  }

  /**
   * The fixture must actually discriminate: identical expected scores everywhere would pass any
   * index mapping. (A constant-output net is a real possibility with a stub weights file.)
   */
  @Test
  public void fixtureScoresAreNotAllEqual() throws Exception {
    JsonNode doc = new ObjectMapper().readTree(FIXTURE.toFile());
    double first = doc.get("fixtures").get(0).get("expected").asDouble();
    boolean varies = false;
    for (JsonNode fx : doc.get("fixtures")) {
      varies |= Math.abs(fx.get("expected").asDouble() - first) > 1e-6;
    }
    assertTrue(varies, "parity fixture scores are all identical — it proves nothing");
  }

  private static Board reconstruct(JsonNode fx) {
    Board b = new Board(NNUEv3Accumulator.BOARD, NNUEv3Accumulator.BOARD);
    for (JsonNode cell : fx.get("cells")) {
      b.setCell(
          cell.get("r").asInt(),
          cell.get("c").asInt(),
          new Cell(cell.get("owner").asInt(), CellKind.valueOf(cell.get("kind").asText())));
    }
    return b;
  }
}
