# .github/workflows/deploy.yml
name: Deploy Application

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Check Formatting with Spotless
        run: ./mvnw spotless:check --file pom.xml

      - name: Build and Test with Maven
        run: ./mvnw -B clean test --file pom.xml

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}

      - name: Update and commit docker-compose.yml
        env:
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_COMMIT_SHA: ${{ github.sha }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git checkout -B deploy
          
          # Replace image tag placeholder with the specific commit SHA
          sed -i "s|image: ghcr.io/${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}:[a-zA-Z0-9.-]*$|image: ghcr.io/${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}:${GITHUB_COMMIT_SHA}|g" docker-compose.yml
          
          git add docker-compose.yml
          git commit -m "ci: Update image tag to ${GITHUB_COMMIT_SHA}"
          git push origin deploy --force

      - name: Trigger Portainer Redeploy Webhook
        uses: distributhor/workflow-webhook@2381f0e9c7b6bf061fb1405bd0804b8706116369 # v3.0.8
        with:
          webhook_url: ${{ secrets.PORTAINER_REDEPLOY_HOOK }}
          webhook_secret: "trigger"
